name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        name: Install

      - run: npm run knex:migrate
      - run: npm run knex:refresh
        name: Run Migrations

      - run: docker-compose up -d mysql mongodb
        name: Start databases infraestructure

      - run: npm run dev
        name: Running app

      - run: docker-compose down
        name: Dispose application infraestructure
